# Rename this file to .credentials.toml

discord_token = "SECRET"
teamspeak_server = "IP:PORT" # NO tsdns
# identity, should change this
teamspeak_identity = "MG0DAgeAAgEgAiAIXJBlj1hQbaH0Eq0DuLlCmH8bl+veTAO2+k9EQjEYSgIgNnImcmKo7ls5mExb6skfK2Tw+u54aeDr0OP1ITsC/50CIA8M5nmDBnmDM/gZ//4AAAAAAAAAAAAAAAAAAAAZRzOI"

# teamspeak server password
# teamspeak_server_password = "my secret"

# use either of the following
# join ts-channel by ID
# teamspeak_channel_id = 1
# join ts-channel by name, use / for nesting
# teamspeak_channel_name = "Default Channel/Nested"
# if required use a password
# teamspeak_channel_password = "some password"

# teamspeak nickname
teamspeak_name = "voice bridge"

# logging stuff, 0-3
verbose = 1
# currently unused
volume = 1.0