# Rename this file to .credentials.toml

discord_token = "SECRET"
teamspeak_server = "IP:PORT" # NO tsdns
# identity, should change this
teamspeak_identity = "MG0DAgeAAgEgAiAIXJBlj1hQbaH0Eq0DuLlCmH8bl+veTAO2+k9EQjEYSgIgNnImcmKo7ls5mExb6skfK2Tw+u54aeDr0OP1ITsC/50CIA8M5nmDBnmDM/gZ//4AAAAAAAAAAAAAAAAAAAAZRzOI"
# join channel ID
teamspeak_channel = 1
# teamspeak nickname
teamspeak_name = "voice bridge"
# logging stuff, 0-3
verbose = 1
# currently unused
volume = 1.0